BOT_TOKEN: "NjU1NTQxODcxMDA2ODQyOserDkx.XfVm8Q._L-Cj736zniWX2YM0rQA-Q6Mg3A" # regen after commits
DEVELOPERS: [477264722991906836, 557163025862361098]
SHARD_COUNT: 1
DEFAULT_COLOR: 0x5C910A
DEFAULT_PREFIX: 's!'
